# Generated by Django 3.2.7 on 2021-09-06 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_flag', models.BooleanField(default=False)),
                ('club_location', models.CharField(blank=True, max_length=40)),
                ('rating', models.IntegerField(default=0)),
                ('antal_vunna', models.IntegerField(default=0)),
                ('ratingf', models.FloatField(default=100)),
                ('snitt', models.FloatField(default=0)),
                ('match_uppdate', models.CharField(blank=True, max_length=100)),
                ('matcher', models.CharField(blank=True, max_length=2000)),
                ('ratings', models.DecimalField(decimal_places=2, default=1000, max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
