# Generated by Django 3.2.7 on 2021-09-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_rating_userprofileinfo_number_played_matches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='antal_vunna',
            new_name='matches_won',
        ),
    ]
